### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by nsaunders** [owickstrom/purescript-trout#9]
@owickstrom thanks for letting me jump in and help out with this library. I would like to release a new version if I can. I have some work on [```purescript-hypertrout```](https://github.com/nicholassaunders/purescript-hypertrout/blob/compiler/0.12/bower.json) and [```purescript-trout-client```](https://github.com/nicholassaunders/purescript-trout-client/blob/compiler/0.12/bower.json) ready to go; but, as you can see by reviewing my links, the ```purescript-trout``` dependency needs to be updated to a numbered version.

Please let me know if you think the version number ```0.10.1``` is not semantically correct given the changes that have been made, or if you have any other concerns. Otherwise, I will attempt a new release in a couple of days.

Thanks again!

**Comment by owickstrom** [comment]
Hey, I'm glad you're here helping out! :) Sounds good with a release, although with the 0.12 compiler upgrades then maybe a 0.11 version would be more clear? Go for it!

**Comment by nsaunders** [comment]
v0.11 it is! Thanks Oskar!

**Comment by nsaunders** [comment]
https://github.com/owickstrom/purescript-trout/releases/tag/v0.11.0
https://pursuit.purescript.org/packages/purescript-trout/0.11.0
